# Generated by Django 4.0.4 on 2023-01-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankName', models.CharField(max_length=10)),
                ('minRankPoints', models.IntegerField(default=1)),
                ('maxRankPoints', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnigPathNumber', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('content', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('content', models.CharField(max_length=250)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('score', models.IntegerField()),
                ('content', models.CharField(max_length=250)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('content', models.CharField(max_length=250)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('friends', models.ManyToManyField(blank=True, null=True, to='BackednApp.user')),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BackednApp.league')),
            ],
        ),
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathsPerWeek', models.IntegerField(default=1)),
                ('singleShowerDuration', models.IntegerField(default=1)),
                ('numberOfShowerPerWeek', models.IntegerField(default=1)),
                ('hasDishwasher', models.BooleanField(default=True)),
                ('numberOfDishwashesPerWeek', models.IntegerField(default=1)),
                ('numberOfWashingMachineUsage', models.IntegerField(default=1)),
                ('waterConsumption', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackednApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Take_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('quiz_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.quiz_answer')),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.quiz_question')),
                ('take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.take')),
            ],
        ),
        migrations.AddField(
            model_name='take',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.user'),
        ),
        migrations.AddField(
            model_name='quiz_answer',
            name='quiz_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.quiz_question'),
        ),
        migrations.CreateModel(
            name='HeatingConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatureInYourHoushold', models.IntegerField(default=1)),
                ('numberOfRooms', models.IntegerField(default=1)),
                ('buildingType', models.IntegerField(default=1)),
                ('heatingConsumption', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackednApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ElectrictyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoursOfPhoneUsage', models.IntegerField(default=1)),
                ('hoursOfComputerUsage', models.IntegerField(default=1)),
                ('hoursOfTVUsage', models.IntegerField(default=1)),
                ('electricityConsumption', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackednApp.user')),
            ],
        ),
    ]
