# Generated by Django 4.1.3 on 2022-12-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnigPathNumber', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('content', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('content', models.CharField(max_length=250)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('score', models.IntegerField()),
                ('content', models.CharField(max_length=250)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('content', models.CharField(max_length=250)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('friends', models.ManyToManyField(null=True, to='BackednApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waterSourceName', models.CharField(max_length=15)),
                ('waterConsumptionPerHour', models.IntegerField()),
                ('unit', models.CharField(max_length=5)),
                ('hoursOfUsage', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Take_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('quiz_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.quiz_answer')),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.quiz_question')),
                ('take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.take')),
            ],
        ),
        migrations.AddField(
            model_name='take',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.user'),
        ),
        migrations.AddField(
            model_name='quiz_answer',
            name='quiz_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.quiz_question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.user'),
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankName', models.CharField(max_length=10)),
                ('minRankPoints', models.IntegerField()),
                ('maxRankPoints', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='HeatingConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatureInYourHoushold', models.IntegerField()),
                ('electricityConsumptionPerHour', models.IntegerField()),
                ('unit', models.CharField(max_length=5)),
                ('hoursOfUsage', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ElectrictyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoursOfPhoneUsage', models.IntegerField(default=1)),
                ('hoursOfComputerUsage', models.IntegerField(default=1)),
                ('hoursOfTVUsage', models.IntegerField(default=1)),
                ('electricityConsumption', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackednApp.user')),
            ],
        ),
    ]
