# Generated by Django 4.1.3 on 2022-12-05 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackednApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatingconsumption',
            name='electricityConsumptionPerHour',
        ),
        migrations.RemoveField(
            model_name='heatingconsumption',
            name='hoursOfUsage',
        ),
        migrations.RemoveField(
            model_name='heatingconsumption',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='league',
            name='user',
        ),
        migrations.RemoveField(
            model_name='waterconsumption',
            name='hoursOfUsage',
        ),
        migrations.RemoveField(
            model_name='waterconsumption',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='waterconsumption',
            name='user',
        ),
        migrations.RemoveField(
            model_name='waterconsumption',
            name='waterConsumptionPerHour',
        ),
        migrations.RemoveField(
            model_name='waterconsumption',
            name='waterSourceName',
        ),
        migrations.AddField(
            model_name='heatingconsumption',
            name='buildingType',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='heatingconsumption',
            name='heatingConsumption',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='heatingconsumption',
            name='numberOfRooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackednApp.league'),
        ),
        migrations.AddField(
            model_name='waterconsumption',
            name='bathsPerWeek',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='waterconsumption',
            name='hasDishwasher',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='waterconsumption',
            name='numberOfDishwashesPerWeek',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='waterconsumption',
            name='numberOfShowerPerWeek',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='waterconsumption',
            name='numberOfWashingMachineUsage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='waterconsumption',
            name='singleShowerDuration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='waterconsumption',
            name='waterConsumption',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='heatingconsumption',
            name='temperatureInYourHoushold',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='league',
            name='maxRankPoints',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='league',
            name='minRankPoints',
            field=models.IntegerField(default=1),
        ),
    ]
