# Generated by Django 4.1.3 on 2022-12-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackednApp', '0006_alter_electrictyconsumption_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatingconsumption',
            name='heatingConsumption',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='waterconsumption',
            name='waterConsumption',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
