# Generated by Django 4.0.4 on 2022-12-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackednApp', '0007_alter_heatingconsumption_heatingconsumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='friend_set', to='BackednApp.user'),
        ),
    ]
