# Generated by Django 4.0.4 on 2022-11-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackednApp', '0009_remove_electrictyconsumption_totalconsumption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electrictyconsumption',
            name='totalusage',
        ),
    ]
