# Generated by Django 4.0.4 on 2022-12-13 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackednApp', '0010_remove_quiz_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='BackednApp.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BackednApp.league'),
        ),
    ]
